In [1]:
print("Hello World!")

Hello World!

In [1]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib as pyplt
import seaborn as sns

## Loading Dataset

In [6]:
# loading the car raw data set 
car=pd.read_csv("2021_Cars_Raw.csv")

In [8]:
car.head()

,OBFCM data source,ID,OBFCM ReportingPeriod,Registration Year,Total fuel consumed (lifetime) (l),Total distance travelled (lifetime) (km),Total distance travelled in charge depleting operation with engine off (lifetime) (km),Total distance travelled in charge depleting operation with engine running (lifetime) (km),Total distance travelled in driver-selectable charge increasing operation (lifetime) (km),Total fuel consumed in charge depleting operation (lifetime) (l),Total fuel consumed in driver-selectable charge increasing operation (lifetime) (l),Total grid energy into the battery (lifetime) (kWh),Used in calculation
0,OEM,55201566,2021,2021,645.57,8077.5,707.6,2561.5,0.0,248.34,0.0,102.4,1
1,OEM,46868086,2021,2021,1363.64,25085.7,10457.4,7449.2,0.0,720.74,0.0,3098.3,1
2,OEM,55201567,2021,2021,121.03,3585.7,2371.1,1064.8,0.0,108.56,0.0,850.7,1
3,OEM,55201568,2021,2021,311.34,6770.1,3605.6,1466.6,0.0,160.05,0.0,1216.7,1
4,OEM,55201574,2021,2021,690.69,10727.7,3226.1,1079.8,0.0,125.23,0.0,1155.0,1

In [9]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 916272 entries, 0 to 916271
Data columns (total 13 columns):
 #   Column                                                                                      Non-Null Count   Dtype
---  ------                                                                                      --------------   -----
 0   OBFCM data source                                                                           916272 non-null  object
 1   ID                                                                                          916272 non-null  int64
 2   OBFCM ReportingPeriod                                                                       916272 non-null  int64
 3   Registration Year                                                                           916272 non-null  int64
 4   Total fuel consumed (lifetime) (l)                                                          916272 non-null  float64
 5   Total distance travelled (lifetime) (km)                                                    916272 non-null  float64
 6   Total distance travelled in charge depleting operation with engine off (lifetime) (km)      444704 non-null  float64
 7   Total distance travelled in charge depleting operation with engine running (lifetime) (km)  444549 non-null  float64
 8   Total distance travelled in driver-selectable charge increasing operation (lifetime)  (km)  448022 non-null  float64
 9   Total fuel consumed in charge depleting operation (lifetime) (l)                            441587 non-null  float64
 10  Total fuel consumed in driver-selectable charge increasing operation (lifetime) (l)         437898 non-null  float64
 11  Total grid energy into the battery (lifetime) (kWh)                                         447005 non-null  float64
 12  Used in calculation                                                                         916272 non-null  int64
dtypes: float64(8), int64(4), object(1)
memory usage: 90.9+ MB

In [11]:
car.describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
ID,916272.0,47412721.14,14267006.73,10.0,46733343.50,51613296.00,54876879.50,6.129939e+07
OBFCM ReportingPeriod,916272.0,2021.00,0.00,2021.0,2021.00,2021.00,2021.00,2.021000e+03
Registration Year,916272.0,2021.00,0.00,2021.0,2021.00,2021.00,2021.00,2.021000e+03
Total fuel consumed (lifetime) (l),916272.0,500.03,673.45,0.0,5.16,268.33,713.74,2.891299e+04
Total distance travelled (lifetime) (km),916272.0,7196.20,20758.64,0.0,29.00,4043.50,10333.00,1.711298e+07
Total distance travelled in charge depleting operation with engine off (lifetime) (km),444704.0,49218.04,3189666.63,0.0,0.00,0.00,408.82,2.147484e+08
Total distance travelled in charge depleting operation with engine running (lifetime) (km),444549.0,47685.60,3188122.77,0.0,0.00,0.00,79.90,2.147484e+08
Total distance travelled in driver-selectable charge increasing operation (lifetime) (km),448022.0,5330228.43,47442242.87,0.0,0.00,0.00,0.00,4.294967e+08
Total fuel consumed in charge depleting operation (lifetime) (l),441587.0,4864.17,319953.74,0.0,0.00,0.00,8.11,2.147484e+07
Total fuel consumed in driver-selectable charge increasing operation (lifetime) (l),437898.0,290042.27,3502749.57,0.0,0.00,0.00,0.00,4.294967e+07
Total grid energy into the battery (lifetime) (kWh),447005.0,659.67,321198.90,0.0,0.00,0.00,54.00,2.147485e+08
Used in calculation,916272.0,0.67,0.47,0.0,0.00,1.00,1.00,1.000000e+00

In [12]:
car.isnull().sum()

OBFCM data source                                                                                  0
ID                                                                                                 0
OBFCM ReportingPeriod                                                                              0
Registration Year                                                                                  0
Total fuel consumed (lifetime) (l)                                                                 0
Total distance travelled (lifetime) (km)                                                           0
Total distance travelled in charge depleting operation with engine off (lifetime) (km)        471568
Total distance travelled in charge depleting operation with engine running (lifetime) (km)    471723
Total distance travelled in driver-selectable charge increasing operation (lifetime)  (km)    468250
Total fuel consumed in charge depleting operation (lifetime) (l)                              474685
Total fuel consumed in driver-selectable charge increasing operation (lifetime) (l)           478374
Total grid energy into the battery (lifetime) (kWh)                                           469267
Used in calculation                                                                                0
dtype: int64

In [13]:
## loading Car aggregated Data set
car_agg=pd.read_csv("2021_Cars_Aggregated.csv")

In [14]:
car_agg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 19 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Manufacturer                                       94 non-null     object
 1   Fuel Type                                          94 non-null     object
 2   Number of vehicles                                 94 non-null     int64
 3   OBFCM Fuel consumption (l/100 km)                  94 non-null     float64
 4   WLTP Fuel consumption (l/100 km)                   94 non-null     float64
 5   absolute gap Fuel consumption (l/100 km)           94 non-null     float64
 6   percentage gap Fuel consumption (%)                94 non-null     float64
 7   OBFCM CO2 emissions (g/km)                         94 non-null     float64
 8   WLTP CO2 emissions (g/km)                          94 non-null     float64
 9   absolute gap CO2 emissions (g/km)                  94 non-null     float64
 10  percentage gap CO2 emissions (%)                   94 non-null     float64
 11  OBFCM Fuel consumption weighted (l/100 km)         94 non-null     float64
 12  WLTP Fuel consumption weighted (l/100 km)          94 non-null     float64
 13  absolute gap Fuel consumption weighted (l/100 km)  94 non-null     float64
 14  percentage gap Fuel consumption weighted (%)       94 non-null     float64
 15  OBFCM CO2 emissions weighted (g/km)                94 non-null     float64
 16  WLTP CO2 emissions weighted (g/km)                 94 non-null     float64
 17  absolute gap CO2 emissions weighted (g/km)         94 non-null     float64
 18  percentage gap CO2 emissions weighted (%)          94 non-null     float64
dtypes: float64(16), int64(1), object(2)
memory usage: 14.1+ KB

In [15]:
car_agg.head()

,Manufacturer,Fuel Type,Number of vehicles,OBFCM Fuel consumption (l/100 km),WLTP Fuel consumption (l/100 km),absolute gap Fuel consumption (l/100 km),percentage gap Fuel consumption (%),OBFCM CO2 emissions (g/km),WLTP CO2 emissions (g/km),absolute gap CO2 emissions (g/km),percentage gap CO2 emissions (%),OBFCM Fuel consumption weighted (l/100 km),WLTP Fuel consumption weighted (l/100 km),absolute gap Fuel consumption weighted (l/100 km),percentage gap Fuel consumption weighted (%),OBFCM CO2 emissions weighted (g/km),WLTP CO2 emissions weighted (g/km),absolute gap CO2 emissions weighted (g/km),percentage gap CO2 emissions weighted (%)
0,KIA,PETROL,1025,6.39,5.56,0.82,14.78,145.50,126.76,18.74,14.78,6.33,5.60,0.72,12.93,144.17,127.66,16.51,12.93
1,SKODA,PETROL,2494,7.29,6.13,1.16,18.96,166.07,139.60,26.47,18.96,7.16,6.12,1.03,16.90,163.03,139.45,23.57,16.90
2,HYUNDAI CZECH,PETROL,1592,7.22,6.26,0.95,15.23,164.36,142.64,21.72,15.23,7.09,6.23,0.86,13.83,161.59,141.95,19.63,13.83
3,TOYOTA,PETROL,6338,5.60,4.99,0.61,12.27,127.52,113.59,13.93,12.27,5.67,5.05,0.62,12.30,129.15,115.00,14.14,12.30
4,MERCEDES-BENZ AG,PETROL,29995,10.53,8.46,2.07,24.45,239.83,192.71,47.13,24.45,10.68,8.67,2.01,23.12,243.30,197.61,45.68,23.12